# CONFIGURACIÓN DEL PROYECTO MASCOTAS
server.port=8082
spring.application.name=mascotas

# Conexión OCI (Usamos la misma Wallet y usuario barraza)
spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high?TNS_ADMIN=./Wallet_UGNFM3WC8EM1NFQI
spring.datasource.username=barraza
spring.datasource.password=ClaseFS123456-

# JPA y Logs
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true