# CONFIGURACIÓN DEL PROYECTO MASCOTAS
server.port=8082
spring.application.name=mascotas

# Conexión OCI (Usando la ruta interna del contenedor)
spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high?TNS_ADMIN=/app/wallet
spring.datasource.username=barraza
spring.datasource.password=ClaseFS123456-

# Forzamos el driver oficial
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true