# Puerto de ejecución
server.port=8080
spring.application.name=hotel-reservas

# Configuración de Conexión a OCI
# Importante: El nombre después de la '@' debe ser exactamente el de tu servicio + '_high'
spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high?TNS_ADMIN=./Wallet_UGNFM3WC8EM1NFQI
spring.datasource.username=barraza
spring.datasource.password=ClaseFS123456-
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true