# CONFIGURACIÓN DEL PROYECTO HOTELES
server.port=8080
spring.application.name=hoteles

# Conexión OCI (Usando la ruta interna del contenedor /app/wallet)
spring.datasource.url=jdbc:oracle:thin:@ugnfm3wc8em1nfqi_high?TNS_ADMIN=/app/wallet
spring.datasource.username=barraza
spring.datasource.password=ClaseFS123456-

# Driver y JPA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true